version: '3.8'

services:
  nginx:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: nginx:1.26
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx:/etc/nginx"
      - "./html:/usr/share/nginx/html"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

# docker-compose exec -it nginx bash