version: '3.8'

#Anchor | Alias 
x-deploy: &deploy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]

services:
  # docker-compose exec -it nginx bash
  nginx:
    image: nginx:1.26
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./static/:/app/resources/static/
    <<: *deploy
    
    # Using `hosts` file for convenience.
  # dns:
  #   build: ./dns/
  #   container_name: dns
  #   restart: unless-stopped
  #   volumes:
  #     - ./dns/named.conf:/etc/bind/named.conf
  #     - ./dns/zone/:/etc/bind/zone/
  #   ports:
  #     - "53:53"
  #     - "53:53/udp"
  #   command: named -c /etc/bind/named.conf -g -u named

  web:
    image: albertalvin/nginx-backend
    container_name: web
    env_file:
      - ./.env/dev.env
    <<: *deploy