version: '3.8'

#Anchor | Alias 
x-deploy: &deploy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]

services:
  nginx:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: nginx:1.26
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx:/etc/nginx"
      - "./html:/usr/share/nginx/html"
    <<: *deploy
# docker-compose exec -it nginx bash
  
  server1:
    image: albertalvin/nginx-demo
    container_name: server1
    ports:
      - "1111:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    <<: *deploy
  
  server2:
    image: albertalvin/nginx-demo
    container_name: server2
    ports:
      - "2222:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    <<: *deploy
